var url ="http://wx.shifuhelp.com/";
// var url = 'http://aksd.qubaotang.cn/';
/*定义路由*/
var app1=angular.module("app1",['ng','ngRoute','ngCookies',"ngTouch","ngAnimate"]);
app1.config(function($routeProvider,$locationProvider){
	$routeProvider
	/*****************************个人中心start*********************************/

	   /*首页界面*/
	.when("/",{
		templateUrl:"ncp/app1/views/me/personalCenter.html",
		controller:"personalCenter"
	})
	    /*收货地址*/
	.when("/addressList",{
		templateUrl:"ncp/app1/views/me/addressList.html",
		controller:"addressList"
	})
		/*新增地址*/
	.when("/addressNew",{
		templateUrl:"ncp/app1/views/me/addressNew.html",
		controller:"addressNew"
	})
		/*绑定手机*/
	.when("/bindMobile",{
		templateUrl:"ncp/app1/views/me/bindMobile.html",
		controller:"bindMobile"
	})
		/*更换手机*/
	.when("/updataMobile",{
		templateUrl:"ncp/app1/views/me/updataMobile.html",
		controller:"updataMobile"
	})
		/*我的收藏*/
	.when("/collectionList",{
		templateUrl:"ncp/app1/views/me/collectionList.html",
		controller:"collectionList"
	})
		/*我的优惠券*/
	.when("/couponList",{
		templateUrl:"ncp/app1/views/me/couponList.html",
		controller:"couponList"
	})
		/*订单消息*/
	.when("/ddNews",{
		templateUrl:"ncp/app1/views/me/ddNews.html",
		controller:"ddNews"
	})
		/*系统消息*/
	.when("/xtNews",{
		templateUrl:"ncp/app1/views/me/xtNews.html",
		controller:"xtNews"
	})
		/*消息*/
	.when("/newsList",{
		templateUrl:"ncp/app1/views/me/newsList.html",
		controller:"newsList"
	})
		/*个人中心*/
	.when("/personalCenter",{
		templateUrl:"ncp/app1/views/me/personalCenter.html",
		controller:"personalCenter"
	})
		/*我的积分*/
	.when("/pointsList",{
		templateUrl:"ncp/app1/views/me/pointsList.html",
		controller:"pointsList"
	})
		/*设置*/
	.when("/setUp",{
		templateUrl:"ncp/app1/views/me/setUp.html",
		controller:"setUp"
	})
		/*订单列表*/
	.when("/order",{
		templateUrl:"ncp/app1/views/me/order.html",
		controller:"order"
	})
		/*订单详情*/
	.when("/orderInfo",{
		templateUrl:"ncp/app1/views/me/orderInfo.html",
		controller:"orderInfo"
	})
		/*订单退款*/
	.when("/orderRefund",{
		templateUrl:"ncp/app1/views/me/orderRefund.html",
		controller:"orderRefund"
	})
		/*订单退款物流*/
	.when("/orderLogistics",{
		templateUrl:"ncp/app1/views/me/orderLogistics.html",
		controller:"orderLogistics"
	})
		/*售后详情*/
	.when("/shInfo",{
		templateUrl:"ncp/app1/views/me/shInfo.html",
		controller:"shInfo"
	})
		/*售后列表*/
	.when("/shList",{
		templateUrl:"ncp/app1/views/me/shList.html",
		controller:"shList"
	})
		/*退货填写物流*/
	.when("/shLogistics",{
		templateUrl:"ncp/app1/views/me/shLogistics.html",
		controller:"shLogistics"
	})
		/*退货物流追踪*/
	.when("/shLogisticsInfo",{
		templateUrl:"ncp/app1/views/me/shLogisticsInfo.html",
		controller:"shLogisticsInfo"
	})
		/*订单评价*/
	.when("/orderEvaluate",{
		templateUrl:"ncp/app1/views/me/orderEvaluate.html",
		controller:"orderEvaluate"
	})
		/*签到成功*/
	.when("/feedback",{
		templateUrl:"ncp/app1/views/me/feedback.html",
		controller:"feedback"
	})
		/*个人资料*/
	.when("/userData",{
		templateUrl:"ncp/app1/views/me/userData.html",
		controller:"userData"
	})
	/*****************************个人中心end*********************************/

 	.otherwise({
        redirectTo: "/"
    })
})